development:
  port: 3312
  mem_limit: 64M
  delta: true
  enable_star: 1
  min_infix_len: 2

test:
  port: 3313
  mem_limit: 64M
  delta: true
  enable_star: 1
  min_infix_len: 2

production:
  port: 3312
  mem_limit: 128M
  delta: true
  enable_star: 1
  min_infix_len: 2